version: '2'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  webserver:
    command: recast-control-center server
    #stdin_open: true
    #tty: true
    image: recastcc
    environment:
      - RECAST_CELERY_REDIS_HOST=redis
      - RECAST_CELERY_REDIS_PORT=6379
      - RECAST_CELERY_REDIS_DB=0
      - RECAST_RESULT_BASE=/home/recast/recaststorage
    volumes:
      - /home/recast/recaststorage:/home/recast/recaststorage
    ports:
      - 80:8000
