resultviewconfig:
  - analysis: 1
    backend: capbackend
    blueprint: recastresultblueprints.capbackend_result.blueprint:blueprint
  - analysis: 2
    backend: capbackend
    blueprint: recastresultblueprints.capbackend_result.blueprint:blueprint
  - analysis: 3
    backend: capbackend
    blueprint: recastresultblueprints.capbackend_result.blueprint:blueprint
