blueprintconfig:
  - prefix: yadageresult
    blueprint: recastresultblueprints.capbackend_result.blueprint:blueprint
defaultviews:
  - plugin: yadageworkflow
    blueprint: recastresultblueprints.capbackend_result.blueprint:blueprint
  - plugin: yadagecombo
    blueprint: recastresultblueprints.capbackend_result.blueprint:blueprint
