blueprintconfig:
  - prefix: yadageresult
    blueprint: recastresultblueprints.capbackend_result.blueprint:blueprint
resultviewconfig:
  - wflowconfigname: dummyconfig
    blueprint: recastresultblueprints.capbackend_result.blueprint:blueprint
