RECASTSTORAGEPATH: "/home/analysis//recast/recaststorage"
RECAST_CONTENT_PATH_TEMPL: "/home/analysis/recast/recaststorage/results/{}/{}"
GITHUBSECRET: ''
ZENODO_TOKEN: ''
RECAST_CELERYAPP: 'recastbackend.productionapp'
